### PR TITLE
Update 1.21

### PR DESCRIPTION
**Pull request by crazymoose77756**

### CODE REVIEW

**Comment by SpeastTV** [comment]
## Crashing

**Prism Launcher**
image
**Minecraft Launcher**
image

**Comment by crazymoose77756** [comment]
> ## Crashing
> **Prism Launcher** image **Minecraft Launcher** image

unable to reproduce.

Fabric version details, mod versions ? etc

**Comment by CopyPaste3** [comment]
also crashing on fabric with latest version of meteor and this addon

The game crashed whilst initializing game
Error: java.lang.IllegalAccessError: class de.damcraft.serverseeker.country.Country tried to access private method 'void net.minecraft.class_2960.<init>(java.lang.String, java.lang.String)' (de.damcraft.serverseeker.country.Country and net.minecraft.class_2960 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @69b794e2)

**Comment by DAMcraft** [comment]
https://github.com/DAMcraft/MeteorServerSeeker/releases/tag/4.4.0

**Pull request closed without merging**
